LojaRazor/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LojaRazor.Models
{
    public class Categoria
    {
        public string Nome { get; set; }

        public Categoria(string nome)
        {
            this.Nome = nome;
        }
    }
}

LojaRazor/Models/Departamento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public class Departamento
    {
        public string Nome { get; set; }

        public IList<Categoria> Categorias { get; set; }

        public Departamento()
        {
            Categorias = new List<Categoria>();
        }
    }
}

LojaRazor/Models/Estado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public enum Estado
    {
        AC, AL, AP, AM,
        BA, CE, DF, ES,
        GO, MA, MT, MS,
        MG, PR, PB, PA,
        PE, PI, RJ, RN,
        RS, RO, RR, SC,
        SE, SP, TO
    }
}

LojaRazor/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public class Produto
    {
        
        public string Nome { get; set; }

        public string Descricao { get; set; }

        public decimal Preco { get; set; }

        public Produto(string nome, string descricao, decimal preco)
        {
            this.Nome = nome;
            this.Descricao = descricao;
            this.Preco = preco;
        }
    }
}

LojaRazor/Models/Sexo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public enum Sexo
    {
        Masculino,
        Feminino
    }
}

LojaRazor/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LojaRazor.Models
{
    public class Usuario
    {
        [Required]
        public String Nome { get; set; }

        [Required]
        public Sexo Sexo { get; set; }

        [Required, EmailAddress]
        public String Email { get; set; }

        [Required, MinLength(3)]
        public String Senha { get; set; }

        [Required]
        public DateTime DataDeNascimento { get; set; }

        [Required]
        public String Endereco { get; set; }

        public Estado Estado { get; set; }

        public String Complemento { get; set; }

        [Required, RegularExpression("\\d{5}-\\d{3}")]
        public String CEP { get; set; }

        public string Observacoes { get; set; }

        public bool RecebePromocoes { get; set; }
    }
}

LojaRazor/Controllers/AutenticacaoController.cs
using LojaRazor.DAO;
using LojaRazor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class AutenticacaoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Autentica(string email, string senha)
        {
            UsuariosDAO dao = new UsuariosDAO();
            Usuario usuarioLogado = dao.Busca(email, senha);
            if (usuarioLogado != null)
            {
                Session["usuarioLogado"] = usuarioLogado.Nome;
                return RedirectToAction("Index", "Home");
            }
            return View("Index");
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
    }
}

LojaRazor/Controllers/HomeController.cs
using LojaRazor.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            ProdutosDAO produtosDAO = new ProdutosDAO();
            ViewBag.Produtos = produtosDAO.Ofertas();
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contato()
        {
            return View();
        }
    }
}

LojaRazor/Controllers/MenuController.cs
using LojaRazor.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Menu/

        public ActionResult Index()
        {
            DepartamentosDAO departamentosDAO = new DepartamentosDAO();
            ViewBag.Departamentos = departamentosDAO.Lista();

            return View();
        }

    }
}

LojaRazor/Controllers/UsuariosController.cs
using LojaRazor.DAO;
using LojaRazor.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaRazor.Controllers
{
    public class UsuariosController : Controller
    {
        public ActionResult Form(string email)
        {
            Usuario u = new Usuario()
            {
                Email = email
            };
            return View(u);
        }

        public ActionResult Cadastra(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                UsuariosDAO dao = new UsuariosDAO();
                dao.Adiciona(usuario);
                Session["usuarioLogado"] = usuario.Nome;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View("Form", usuario);
            }
        }

    }
}

LojaRazor/Views/Autenticacao/Index.cshtml
<div class="hero-unit span6">
    
    <h2>Login</h2>

    <p>Já Possui Cadastro? Então faça seu login</p>
    <form action="@Url.Action("Autentica", "Autenticacao")">
        <input type="text" class="input-block-level" placeholder="E-mail" />

        <input type="password" class="input-block-level" placeholder="Senha" />

        <input type="submit" class="btn btn-large btn-primary" value="Fazer Login" />
    </form>
</div>

<div class="hero-unit span6">
    <h2>Novo Usuário?</h2>

    <p>Se você ainda não tem um cadastro, informe qual é o e-mail que você deseja associar com sua conta</p>

    <form action="@Url.Action("Form", "Usuarios")">
        <input type="text" class="input-block-level" placeholder="E-mail" name="Email"/>

        <input type="submit" class="btn btn-large btn-primary" value="Criar Conta" />
    </form>
</div>

LojaRazor/Views/Home/Index.cshtml
<!-- conteúdo -->
<div class="hero-unit">
    <h1>Queima de estoque</h1>
    <p>Monitores com 20% de desconto no cartão de crédito em 50 vezes sem juros</p>
</div>
<div class="row-fluid">
    <!-- produtos aqui -->
    @foreach (var produto in ViewBag.Produtos)
    {
        <div class="span4">
            <p>@produto.Nome</p>
            <p>@produto.Descricao</p>
            <p>@produto.Preco</p>
        </div>
    }
</div>

LojaRazor/Views/Menu/Index.cshtml
@{
    Layout = null;
}
<div class="sidebar-nav well">
    <ul class="nav nav-list">
        @foreach (var departamento in ViewBag.Departamentos)
        {
            <li class="nav-header">@departamento.Nome</li>
            foreach (var categoria in departamento.Categorias)
            {
                <li>@categoria.Nome</li>
            }
        }
    </ul>
</div>

LojaRazor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Styles.Render("~/bundles/estilos")
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            @Html.ActionLink("Loja Razor", "Index", "Home", null, new { @class = "brand" })
            <ul class="nav">
                <li>@Html.ActionLink("Sobre", "About", "Home",null, new { @class = "brand" })</li>
                <li>@Html.ActionLink("Contato", "Contato", "Home", null, new { @class = "brand" })</li>
            </ul>
            <p class="navbar-text pull-right">
                @if (Session["usuarioLogado"] != null)
                {
                    @: Bem-Vindo
                    @Session["usuarioLogado"]
                    @Html.ActionLink("Logout", "Logout", "Autenticacao")
                }
                else
                {
                   
                    @Html.ActionLink("Login", "Index", "Login")
                    @: ou
                    @Html.ActionLink("Cadastre-se", "Form", "Usuarios")
                }
            </p>
        </div>
    </div>
    <div class="span3">
        <!-- menu -->
        @Html.Action("Index","Menu") 
    </div>
    <div class="span9">
        @RenderBody()
    </div>
    @RenderSection("Scripts", false)
</body>
</html>

LojaRazor/Views/Shared/_MenuSuperior.cshtml
@{ Layout = null;}
@using LojaRazor.Internacionalizacao

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">

            @Html.ActionLink("Loja Razor", "Index", "Home", null, new { @class = "brand" })

        <ul class="nav">
            <li>@Html.ActionLink(Mensagem.Sobre, "About", "Home")</li>
            <li>@Html.ActionLink(Mensagem.Contato, "Contato", "Home")</li>
        </ul>
        <p class="navbar-text pull-right">
            @if (Session["usuarioLogado"] != null)
            {
                @: Bem-Vindo
                @Session["usuarioLogado"]
                @Html.ActionLink(Mensagem.Logout, "Logout", "Autenticacao")
            }
            else
            {
                @: @Mensagem.OlaVisitante,
                @Html.ActionLink(Mensagem.Login, "Index", "Login")
                @: @Mensagem.Ou
                @Html.ActionLink(Mensagem.Cadastrese, "Form", "Usuarios")
            }
        </p>
    </div>
</div>

LojaRazor/Views/Usuarios/Form.cshtml
@model LojaRazor.Models.Usuario
@using (Html.BeginForm("Cadastra", "Usuarios", FormMethod.Post))
{

    <fieldset>
        <legend>Dados Pessoais</legend>
        @Html.LabelFor(usuario => usuario.Nome, "Nome:")
        @Html.TextBoxFor(usuario => usuario.Nome)
        @Html.ValidationMessageFor(usuario => usuario.Nome)

        <div class="control-group">
            @Html.LabelFor(usuario => usuario.Sexo, "Sexo:")
            <label class="inline radio">
                @Html.RadioButtonFor(usuario => usuario.Sexo, LojaRazor.Models.Sexo.Masculino) Masculino
            </label>

            <label class="inline radio">
                @Html.RadioButtonFor(usuario => usuario.Sexo, LojaRazor.Models.Sexo.Feminino) Feminino
            </label>
        </div>

        @Html.LabelFor(usuario => usuario.Estado)
        @Html.DropDownListFor(usuario => usuario.Estado, new SelectList(Enum.GetValues(typeof(LojaRazor.Models.Estado))))

        @Html.LabelFor(usuario => usuario.Email, "Email:")
        @Html.TextBoxFor(usuario => usuario.Email)
        @Html.ValidationMessageFor(usuario => usuario.Email)

        @Html.LabelFor(usuario => usuario.DataDeNascimento, "Data de Nascimento:")
        @Html.TextBoxFor(usuario => usuario.DataDeNascimento)
        @Html.ValidationMessageFor(usuario => usuario.DataDeNascimento)

        @Html.LabelFor(usuario => usuario.Senha, "Senha:")
        @Html.PasswordFor(usuario => usuario.Senha)
        @Html.ValidationMessageFor(usuario => usuario.Senha)

    </fieldset>
    <fieldset>
        <legend>Dados de Entrega</legend>
        @Html.LabelFor(usuario => usuario.Endereco, "Endereço:")
        @Html.TextBoxFor(usuario => usuario.Endereco)
        @Html.ValidationMessageFor(usuario => usuario.Endereco)

        @Html.LabelFor(usuario => usuario.Complemento, "Complemento")
        @Html.TextBoxFor(usuario => usuario.Complemento)
        @Html.ValidationMessageFor(usuario => usuario.Complemento)

        @Html.LabelFor(usuario => usuario.CEP, "CEP:")
        @Html.TextBoxFor(usuario => usuario.CEP)
        @Html.ValidationMessageFor(usuario => usuario.CEP)

        @Html.LabelFor(usuario => usuario.Observacoes, "Observação:")
        @Html.TextAreaFor(usuario => usuario.Observacoes)
        @Html.ValidationMessageFor(usuario => usuario.Observacoes)

    </fieldset>
    <div>
        @Html.LabelFor(usuario => usuario.RecebePromocoes, "RecebePromoções")
        @Html.CheckBoxFor(usuario => usuario.RecebePromocoes)
        @Html.ValidationMessageFor(usuario => usuario.RecebePromocoes)

        Desejo receber informações sobre promoções
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-large" />
}

@section Scripts{
    @Styles.Render("~/bundles/scripts")

}