LojaWeb/Controllers/VendasController.cs
using LojaWeb.DAO;
using LojaWeb.Entidades;
using LojaWeb.Models;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaWeb.Controllers
{
    public class VendasController : Controller
    {
        ISession session;
        VendasDAO vendasDao;
        UsuariosDAO usuariosDao;
        ProdutosDAO produtosDao;
        

        public VendasController(VendasDAO vendasDao, UsuariosDAO usuariosDao, ProdutosDAO produtosDao)
        {
            this.vendasDao = vendasDao;
            this.usuariosDao = usuariosDao;
            this.produtosDao = produtosDao;
        }
        
        public ActionResult Index()
        {
            IList<Venda> vendas = vendasDao.Lista();
            return View(vendas);
        }
        public ActionResult ListaProdutos()
        {
            IList<Produto> produtos = produtosDao.Lista();
            ViewBag.ProdutosNoCarrinho = this.Carrinho.Produtos.Count;
            return View(produtos);
        }
        public ActionResult AdicionaProduto(int produtoId)
        {
            Produto produto = produtosDao.BuscaPorId(produtoId);
            this.Carrinho.Adiciona(produto);
            return RedirectToAction("ListaProdutos");
        }
        public ActionResult FechaPedido()
        {
            IList<Produto> produtos = this.Carrinho.Produtos;
            IList<PessoaFisica> usuarios = usuariosDao.Lista() ;
            ViewBag.Usuarios = usuarios;
            return View(produtos);
        }
        public ActionResult CompletaPedido(int usuarioId)
        {
            Usuario usuario = usuariosDao.BuscaPorId(usuarioId);
            Venda venda = this.Carrinho.CriaVenda(usuario);
            // grava venda
            vendasDao.GravaVenda(venda);
            this.Carrinho = new Carrinho();
            return RedirectToAction("Index");
        }
        public ActionResult LimpaCarrinho()
        {
            this.Carrinho = new Carrinho();
            return RedirectToAction("ListaProdutos");
        }

        // O Valor da propriedade Carrinho é armazenado na sessão
        private Carrinho Carrinho
        {
            get
            {
                Carrinho atual = Session["Carrinho"] as Carrinho;
                if (atual == null)
                {
                    atual = new Carrinho();
                    Session["Carrinho"] = atual;
                }
                return atual;
            }
            set
            {
                Session["Carrinho"] = value;
            }
        }

        
    }
}

LojaWeb/Views/Vendas/FechaPedido.cshtml
@{
    ViewBag.Title = "Fecha Pedido";
}

<h2>Fechar Pedido</h2>

<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var produto in @Model) 
        {
            <tr>
                <td>@produto.Nome</td>
                <td>@produto.Preco</td>
            </tr>
        }
    </tbody>
</table>

Escolha o usuário para o pedido:

<form action="@Url.Action("CompletaPedido", "Vendas")" method="post">
    <select name="usuarioId">
        @foreach (var usuario in @ViewBag.Usuarios)
        {
            <option value="@usuario.Id">@usuario.Nome</option>
        }
    </select>
    <input type="submit" value="Comprar"/>
</form>

LojaWeb/Views/Vendas/Index.cshtml
@model System.Collections.Generic.IEnumerable<LojaWeb.Entidades.Venda>
@{
    ViewBag.Title = "Index";
}

<h2>Lista de Vendas</h2>

@Html.ActionLink("Comprar", "ListaProdutos", "Vendas")

<table>
    <thead>
        <tr>
            <th>Usuário</th>
            <th>Produtos</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var venda in @Model)
        {
            <tr>
                <td>@venda.Cliente.Nome</td>
                <td>
                    @(string.Join(", ", from p in venda.Produtos select p.Nome))
                </td>
            </tr>
        }
    </tbody>
</table>

LojaWeb/Views/Vendas/ListaProdutos.cshtml
@{
    ViewBag.Title = "ListaProdutos";
}

<h2>ListaProdutos</h2>

@Html.ActionLink("Fechar Pedido", "FechaPedido", "Vendas")
@Html.ActionLink("Limpar o carrinho", "LimpaCarrinho", "Vendas")

Produtos no carrinho: @ViewBag.ProdutosNoCarrinho

<table>
    <thead>
        <tr>
            <th>Produto</th>
            <th>Categoria</th>
            <th>Preço</th>
            <th>Comprar?</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var produto in @Model)
        {
            <tr>
                <td>@produto.Nome</td>
                <td>@produto.Categoria.Nome</td>
                <td>@produto.Preco</td>
                <td>@Html.ActionLink("Comprar", "AdicionaProduto", new {produtoId=produto.Id})</td>
            </tr>
        }
    </tbody>
</table>