LojaWeb/Controllers/CategoriasController.cs
using LojaWeb.Entidades;
using LojaWeb.Infra;
using LojaWeb.Models;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LojaWeb.DAO;

namespace LojaWeb.Controllers
{
    public class CategoriasController : Controller
    {
        //
        // GET: /Categorias/
        ISession session = NHibernateHelper.AbreSession();
        private CategoriasDAO dao;

        public CategoriasController(CategoriasDAO dao)
        {
            this.dao = dao;
        }

        public ActionResult Index()
        {
            IList<Categoria> categorias = dao.Lista();
            return View(categorias);
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Adiciona(Categoria categoria)
        {
            ISession session = NHibernateHelper.AbreSession();
            CategoriasDAO dao = new CategoriasDAO(session);
            dao.Adiciona(categoria);
            return RedirectToAction("Visualiza", categoria);
        }

        public ActionResult Remove(int id)
        {

            return RedirectToAction("Index");
        }

        public ActionResult Visualiza(Categoria categoria)
        {
            ISession session = NHibernateHelper.AbreSession();
            CategoriasDAO dao = new CategoriasDAO(session);
            Categoria categorias = dao.BuscaPorId(categoria.Id);
            return View(categorias);
        }

        public ActionResult Atualiza(Categoria categoria)
        {
            ISession session = NHibernateHelper.AbreSession();
            CategoriasDAO dao = new CategoriasDAO(session);
            dao.Atualiza(categoria);
            return View("Visualiza", categoria);
        }

        public ActionResult CategoriasEProdutos()
        {
            IList<Categoria> categorias = dao.Lista();
            return View(categorias);
        }

        public ActionResult BuscaPorNome(string nome)
        {
            IList<Categoria> categorias = dao.BuscaPorNome(nome);
            return View(categorias);
        }

        public ActionResult NumeroDeProdutosPorCategoria()
        {
            IList<ProdutosPorCategoria> produtosPorCategoria = dao.ListaNumeroDeProdutosPorCategoria();
            return View(produtosPorCategoria);
        }


    }
}

LojaWeb/Controllers/HerancaController.cs
using LojaWeb.DAO;
using LojaWeb.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaWeb.Controllers
{
    public class HerancaController : Controller
    {
        //private UsuariosDAO usuariosDAO;

        //public HerancaController(UsuariosDAO usuariosDAO)
        //{
        //    this.usuariosDAO = usuariosDAO;
        //}
        //public ActionResult FormPessoaFisica()
        //{
        //    return View();
        //}
        //public ActionResult AdicionaPessoaFisica(PessoaFisica pessoaFisica)
        //{
        //    usuariosDAO.Adiciona(pessoaFisica);
        //    return RedirectToAction("Index", "Usuarios");
        //}
        //public ActionResult FormPessoaJuridica()
        //{
        //    return View();
        //}
        //public ActionResult AdicionaPessoaJuridica(PessoaJuridica pessoaJuridica)
        //{
        //    usuariosDAO.Adiciona(pessoaJuridica);
        //    return RedirectToAction("Index", "Usuarios");
        //}
    }
}

LojaWeb/Controllers/ProdutosController.cs
using log4net;
using LojaWeb.DAO;
using LojaWeb.Entidades;
using LojaWeb.Infra;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LojaWeb.Controllers
{
    public class ProdutosController : Controller
    {
        //
        // GET: /Produtos/
        private ISession session;
        private ProdutosDAO produtosdao;

        public ProdutosController(ProdutosDAO dao)
        {
            this.produtosdao = dao;
        }

        public ActionResult Index()
        {
            //ISession session = NHibernateHelper.AbreSession();
            //ProdutosDAO dao = new ProdutosDAO(session);
            IList<Produto> produtos = produtosdao.Lista();
            return View(produtos);
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Adiciona(Produto produto)
        {
            if (produto.Categoria.Id == 0)
            {
                produto.Categoria = null;
            }

            session = NHibernateHelper.AbreSession();
            produtosdao = new ProdutosDAO(session);
            produtosdao.Adiciona(produto);
            return RedirectToAction("Visualiza", new { id = produto.Id });
        }

        public ActionResult Remove(int id)
        {
            produtosdao.Remove(id);
            return RedirectToAction("Index");
        }

        public ActionResult Visualiza(int id)
        {
            //ISession session = NHibernateHelper.AbreSession();
            //ProdutosDAO dao = new ProdutosDAO(session);
            //Produto p = dao.BuscaPorId(id);
            Produto p = produtosdao.BuscaPorId(id);            
            //session.Close();
            return View(p);
        }

        public ActionResult Atualiza(Produto produto)
        {
            ISession session = NHibernateHelper.AbreSession();
            ProdutosDAO dao = new ProdutosDAO(session);
            dao.Atualiza(produto);
            session.Close();
            return RedirectToAction("Index");
        }

        public ActionResult ProdutosComPrecoMinimo(double? preco)
        {
            ViewBag.Preco = preco;
            IList<Produto> produtos = produtosdao.ProdutosComPrecoMaiorDoQue(preco);
            return View(produtos);

        }

        public ActionResult ProdutosDaCategoria(string nomeCategoria)
        {
            ViewBag.NomeCategoria = nomeCategoria;
            IList<Produto> produtos = produtosdao.ProdutosDaCategoria(nomeCategoria);
            return View(produtos);
        }

        public ActionResult ProdutosDaCategoriaComPrecoMinimo(double? preco, string nomeCategoria)
        {
            ViewBag.Preco = preco;
            ViewBag.NomeCategoria = nomeCategoria;
            IList<Produto> produtos = produtosdao.ProdutosDaCategoriaComPrecoMaiorDoQue(preco, nomeCategoria);
            return View(produtos);
        }

        public ActionResult BuscaDinamica(double? preco, string nome, string nomeCategoria)
        {
            ViewBag.Preco = preco;
            ViewBag.Nome = nome;
            ViewBag.NomeCategoria = nomeCategoria;

            IList<Produto> produtos = new List<Produto>();
            return View(produtos);
        }
        public ActionResult ListaPaginada(int? pagina)
        {
            int paginaAtual = pagina.GetValueOrDefault(1);
            ViewBag.Pagina = paginaAtual;
            IList<Produto> produtos = produtosdao.ListaPaginada(paginaAtual);
            return View(produtos);
        }
    }
}

LojaWeb/Controllers/UsuariosController.cs
using LojaWeb.DAO;
using LojaWeb.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LojaWeb.Infra;
using NHibernate;

namespace LojaWeb.Controllers
{
    public class UsuariosController : Controller
    {
        //
        // GET: /Usuarios/
        ISession session = NHibernateHelper.AbreSession();
        UsuariosDAO usuariosDao;

        public UsuariosController(UsuariosDAO usuariosDao)
        {
            this.usuariosDao = usuariosDao;
        }

        public ActionResult Index()
        {
            IList<PessoaFisica> usuarios = usuariosDao.Lista();
            return View(usuarios);
        }

        public ActionResult Form()
        {
            return View();
        }

        public ActionResult Adiciona(PessoaFisica usuario)
        {
            usuariosDao.Adiciona(usuario);
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            session.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult Visualiza(int id)
        {
            Usuario usuario = usuariosDao.BuscaPorId(id);
            return View(usuario);
        }

        public ActionResult Atualiza(PessoaFisica usuario)
        {
            usuariosDao.Atualiza(usuario);
            return RedirectToAction("Index");
        }

    }
}

LojaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Loja Web - NHibernate", "Index", "Home")</p>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p><a href="http://online.caelum.com.br">Caelum Online - NHibernate</a></p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

LojaWeb/Views/Shared/_ListaCategorias.cshtml
@Html.ActionLink("Nova Categoria", "Form", "Categorias")

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Visualizar</th>
            <th>Remover</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var categoria in @Model) 
        {
            <tr>
                <td>@categoria.Id</td>
                <td>@categoria.Nome</td>
                <td><a href="@Url.Action("Visualiza", "Categorias", new {id = categoria.Id})">Visualizar</a></td>
                <td><a href="@Url.Action("Remove", "Categorias", new {id = categoria.Id})">Remover</a></td>
            </tr>
        }
    </tbody>
</table>

LojaWeb/Views/Shared/_ListaProdutos.cshtml
@Html.ActionLink("Novo Produto", "Form", "Produtos")

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Preço</th>
            @*<th>Categoria</th>*@
            <th>Visualizar</th>
            <th>Remover</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var produto in @Model) 
        {
            <tr>
                <td>@produto.Id</td>
                <td>@produto.Nome</td>
                <td>@produto.Preco</td>
                @*<td>@produto.Categoria.Nome</td>*@
                <td><a href="@Url.Action("Visualiza", "Produtos", new {id = produto.Id})">Visualizar</a></td>
                <td><a href="@Url.Action("Remove", "Produtos", new {id = produto.Id})">Remover</a></td>
            </tr>
        }
    </tbody>
</table>

LojaWeb/Views/Shared/_ListaUsuarios.cshtml
@Html.ActionLink("Novo Usuário", "Form", "Usuarios")
@Html.ActionLink("Nova Pessoa Física", "FormPessoaFisica", "Heranca")
@Html.ActionLink("Nova Pessoa Jurídica", "FormPessoaJuridica", "Heranca")

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Visualizar</th>
            <th>Remover</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var usuario in @Model) 
        {
            <tr>
                <td>@usuario.Id</td>
                <td>@usuario.Nome</td>
                <td><a href="@Url.Action("Visualiza", "Usuarios", new {id = usuario.Id})">Visualizar</a></td>
                <td><a href="@Url.Action("Remove", "Usuarios", new {id = usuario.Id})">Remover</a></td>
            </tr>
        }
    </tbody>
</table>